@startuml IKC App Class/Database Diagram
title IKC App Class/Database Diagram
!theme vibrant
skinparam linetype ortho
skinparam ConditionEndStyle hline

entity project {
    * ProjectTitle
    * ProjectNumber
    * Funding
    * projectStartDate
    * projectEndDate
    * projectPartners: [partnerOrg]
    * ikcReports: [ikcReport]
}

entity contributor {
    * annualSalary
    * dailyHours
    * benefitRatePercentage
    * partnerOrg
}

entity partnerOrg {
    * partnerName
    contributors: [contributor]
}

partnerOrg }o--|{ project
partnerOrg ||--|{ contributor

entity ikcReport {
    * partnerName
    * submittedby: contributor
    * ikcReportStartDate
    * ikcReportEndDate
    contributions: [contribItems]

    submissionData
}

ikcReport }o..|| project 
ikcReport }o..|| partnerOrg

entity submissionData {
    * ikcReport
    * nameOfRep
    * signatureOfRep
    * date
}

submissionData |o--|| ikcReport


entity contribItem {
    * id
    * correlationId: {contributorId, projectId}
    * date
    * details
}

contribItem }o--|| ikcReport

entity hourContribution {
    * id {contribItemId}
    * hours
    * hourlyPay
    * benefitRatePercentage
}

entity otherContribution {
    * id {contribItemId}
    * itemName
    * value
}

note as idNote
id are being inherited as a foreignKey from contribItem
as it will be acting as the parent table
end note

idNote .. hourContribution
idNote .. otherContribution

otherContribution --|> contribItem
hourContribution --|> contribItem
contributor ||--o{ contribItem
project ||--o{ contribItem

@enduml