@startuml IKC App Login Flow
title IKC App Login Flow
!theme vibrant
skinparam linetype polyline
skinparam ConditionEndStyle hline

start
if(has account?) then (no)
    repeat 
        #pink:send one time link to person;
        :set up account;
        
        note right
            may instead prefer having only
            local accounts within conestga
            for initalizing this, then require
            a google/azure for all external?
        end note

        if(local auth or google/azure?) then (local auth)
            :require email, and phone number;
        else (google/azure auth)
            :require google/azure connection request;
        endif
        :request addition to a organization
        and project to administrator;
        note right
            maybe one time link is admin
            specific so it knows who to notify?
        end note

        repeat while (account creation successful?) is (false)
        ->true;
        #paleGreen:accont created;
    else (true)
    
    endif
label login
while (access site) is (no session)
    #lightYellow:prompt login using azure, google
    or local account;
    if(is local or google/azure login?) then (local login)
        :request username/email and password;
        :send OTP by text for extra authentication;
    else (azure/google login)
        :trigger google/azure login request;
    endif

    if (authentication result is valid) then (no)
    else (yes)
        if (has recognized email or domain) then (no)
        else (yes)
        #paleGreen:create session;
        break

        endif
    endif
    #pink:repeat login attempt;
    note left
        maybe set login limits?
        will also need to remeber which login
        type to redirect back properly.
    end note
endwhile (has session)

if(assigned to a project?)then (yes)
else (no)
    end
endif
#paleGreen:allow access;

stop
@enduml